// Student screens in the child's language. The maths itself always stays in digits and a/b form.
import type { Lang } from "../../../teacher/[code]/_dashboard/api";

export const LANGS: { id: Lang; name: string }[] = [
  { id: "en", name: "English" },
  { id: "hi", name: "हिन्दी" },
  { id: "kn", name: "ಕನ್ನಡ" },
];

const en = {
  welcome: "Join your class",
  yourName: "Your name",
  namePlaceholder: "Type your first name",
  pickLanguage: "Choose your language",
  start: "Start",
  joining: "Joining…",
  question: (n: number, m: number) => `Question ${n} of ${m}`,
  typeHint: "Type your answer, like 3/4 or 1 1/2",
  check: "Check",
  correct: "Correct!",
  notQuite: "Not quite",
  answerIs: (a: string) => `The answer is ${a}`,
  next: "Next question",
  fixNow: "Fix this now",
  writing: "Your mini-lesson is being written…",
  lesson: "Your mini-lesson",
  practise: "Practise",
  showAnswer: "Show answer",
  tryTwo: "Try 2 more to close this gap",
  checkBoth: "Check both",
  gapClosed: "Gap closed!",
  keepGoing: "Keep practising. You're getting closer.",
  teacherTold: "Your teacher can see this.",
  continueQuiz: "Continue",
  allDone: "All done for today!",
  allDoneNote: "Great work. Your teacher will see how you did.",
  caughtUp: "You're all caught up.",
  translationMissing: "English (translation unavailable)",
  noClass: "No class has this code. Ask your teacher for the class code.",
  offline: "Can't reach the class. Check your internet and try again.",
  tryAgain: "Try again",
};

type Words = typeof en;

const hi: Words = {
  welcome: "अपनी कक्षा से जुड़ें",
  yourName: "तुम्हारा नाम",
  namePlaceholder: "अपना पहला नाम लिखो",
  pickLanguage: "अपनी भाषा चुनो",
  start: "शुरू करें",
  joining: "जुड़ रहे हैं…",
  question: (n, m) => `प्रश्न ${n} / ${m}`,
  typeHint: "अपना उत्तर लिखो, जैसे 3/4 या 1 1/2",
  check: "जाँचो",
  correct: "सही!",
  notQuite: "थोड़ी चूक",
  answerIs: (a) => `सही उत्तर ${a} है`,
  next: "अगला प्रश्न",
  fixNow: "अभी ठीक करो",
  writing: "तुम्हारा छोटा पाठ लिखा जा रहा है…",
  lesson: "तुम्हारा छोटा पाठ",
  practise: "अभ्यास",
  showAnswer: "उत्तर देखो",
  tryTwo: "यह कमी दूर करने के लिए 2 और प्रश्न करो",
  checkBoth: "दोनों जाँचो",
  gapClosed: "कमी दूर हो गई!",
  keepGoing: "अभ्यास करते रहो। तुम करीब हो।",
  teacherTold: "तुम्हारे शिक्षक यह देख सकते हैं।",
  continueQuiz: "आगे बढ़ो",
  allDone: "आज का काम पूरा!",
  allDoneNote: "बहुत बढ़िया। तुम्हारे शिक्षक देखेंगे कि तुमने कैसा किया।",
  caughtUp: "तुम्हारा सब काम पूरा है।",
  translationMissing: "English (अनुवाद उपलब्ध नहीं)",
  noClass: "इस कोड की कोई कक्षा नहीं है। अपने शिक्षक से कोड पूछो।",
  offline: "कक्षा से जुड़ नहीं पा रहे। इंटरनेट जाँचो और फिर से कोशिश करो।",
  tryAgain: "फिर से कोशिश करो",
};

const kn: Words = {
  welcome: "ನಿಮ್ಮ ತರಗತಿಗೆ ಸೇರಿ",
  yourName: "ನಿಮ್ಮ ಹೆಸರು",
  namePlaceholder: "ನಿಮ್ಮ ಮೊದಲ ಹೆಸರು ಬರೆಯಿರಿ",
  pickLanguage: "ನಿಮ್ಮ ಭಾಷೆ ಆರಿಸಿ",
  start: "ಪ್ರಾರಂಭಿಸಿ",
  joining: "ಸೇರುತ್ತಿದೆ…",
  question: (n, m) => `ಪ್ರಶ್ನೆ ${n} / ${m}`,
  typeHint: "ನಿಮ್ಮ ಉತ್ತರ ಬರೆಯಿರಿ, ಉದಾ 3/4 ಅಥವಾ 1 1/2",
  check: "ಪರಿಶೀಲಿಸಿ",
  correct: "ಸರಿ!",
  notQuite: "ಸ್ವಲ್ಪ ತಪ್ಪಾಗಿದೆ",
  answerIs: (a) => `ಸರಿಯಾದ ಉತ್ತರ ${a}`,
  next: "ಮುಂದಿನ ಪ್ರಶ್ನೆ",
  fixNow: "ಈಗಲೇ ಸರಿಪಡಿಸಿ",
  writing: "ನಿಮ್ಮ ಕಿರು ಪಾಠ ಸಿದ್ಧವಾಗುತ್ತಿದೆ…",
  lesson: "ನಿಮ್ಮ ಕಿರು ಪಾಠ",
  practise: "ಅಭ್ಯಾಸ",
  showAnswer: "ಉತ್ತರ ನೋಡಿ",
  tryTwo: "ಈ ಕೊರತೆ ನೀಗಿಸಲು ಇನ್ನೂ 2 ಪ್ರಶ್ನೆ ಮಾಡಿ",
  checkBoth: "ಎರಡನ್ನೂ ಪರಿಶೀಲಿಸಿ",
  gapClosed: "ಕೊರತೆ ನೀಗಿದೆ!",
  keepGoing: "ಅಭ್ಯಾಸ ಮುಂದುವರಿಸಿ. ನೀವು ಹತ್ತಿರದಲ್ಲಿದ್ದೀರಿ.",
  teacherTold: "ನಿಮ್ಮ ಶಿಕ್ಷಕರು ಇದನ್ನು ನೋಡಬಹುದು.",
  continueQuiz: "ಮುಂದುವರಿಸಿ",
  allDone: "ಇಂದಿನ ಕೆಲಸ ಮುಗಿಯಿತು!",
  allDoneNote: "ಚೆನ್ನಾಗಿ ಮಾಡಿದ್ದೀರಿ. ನೀವು ಹೇಗೆ ಮಾಡಿದಿರಿ ಎಂದು ಶಿಕ್ಷಕರು ನೋಡುತ್ತಾರೆ.",
  caughtUp: "ನಿಮ್ಮ ಎಲ್ಲಾ ಕೆಲಸ ಮುಗಿದಿದೆ.",
  translationMissing: "English (ಅನುವಾದ ಲಭ್ಯವಿಲ್ಲ)",
  noClass: "ಈ ಕೋಡ್‌ನ ತರಗತಿ ಇಲ್ಲ. ನಿಮ್ಮ ಶಿಕ್ಷಕರಿಂದ ಕೋಡ್ ಕೇಳಿ.",
  offline: "ತರಗತಿಗೆ ಸಂಪರ್ಕವಾಗುತ್ತಿಲ್ಲ. ಇಂಟರ್ನೆಟ್ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  tryAgain: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
};

export const WORDS: Record<Lang, Words> = { en, hi, kn };
